import "~/styles/globals.css";

import { Roboto } from "next/font/google";
import { Navbar } from "./_components/Navbar";
import { Sidebar } from "./_components/Sidebar";
import { AppContextProvider } from "./Context/state";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Markdown",
  description: "Generated by okori",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-roboto ${roboto.variable} `}>
        <AppContextProvider>
          <main className="flex h-screen flex-row">
            <Sidebar />
            <section className="h-full w-full flex-grow overflow-auto">
              <Navbar />
              {children}
            </section>
          </main>
        </AppContextProvider>
      </body>
    </html>
  );
}
